### PR TITLE
Create PKGBUILD-python-virtualenv

### PR DESCRIPTION
**Pull request by D3vil0p3r**
Example: https://github.com/BlackArch/blackarch/pull/4382/files#diff-4052d14687365b012298fd93b3ccfe8e99e6e71db7756c806cd9b188ccb49975

### CODE REVIEW

**Comment by noraj** [comment]
It was done through https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-standalone and https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/python-standalone.install

**Comment by D3vil0p3r** [comment]
Yes but in the Python Standalone it asks for a Python .py file and a separated install file. Not sure if, in this case, when you remove the pkg, also the venv will be deleted.

In the PR case, you dont have post install script, the venv is removed after pkg uninstall, and in binary you pass the module name of the tool instead if the direct .py file path.

**Comment by noraj** [comment]
> Yes but in the Python Standalone it asks for a Python .py file

Not necessarilly, we could add a comment `# or` `source /usr/share/$pkgname/venv/bin/activate\n
exec python -m $pkgname "\$@"`.

> and a separated install file.

It's to avoid having the venv in the built archive, as on `post_install` is done after the install directly on the host. And you actually need the `.install` for `post_upgrade`, else you venv will be outdated at the first update.

> Not sure if, in this case, when you remove the pkg, also the venv will be deleted.

Need to check, if it does not, we could add [post_remove](https://wiki.archlinux.org/title/PKGBUILD#install) in .install.

**Review by noraj — CHANGES_REQUESTED** [review]
IMHO this template should be refused as a .install is required to update the venv as explained in https://github.com/BlackArch/blackarch-pkgbuilds/pull/27#issuecomment-2501456216.

I'd rather improve python-standalone.install with a `post_remove` and `PKGBUILD-python-standalone` with an alternative wrapper.

**Comment by noraj** [comment]
FYI, `python -m NAME` is deprecated, once the venv has been activated only `name` is enough as it gets loaded into the PATH. But if one prefer an absolute path to ensure what's going on, one can use `/usr/share/$pkgname/venv/bin/$pkgname`.

**Comment by D3vil0p3r** [comment]
Thanks man

**Comment by noraj** [comment]
https://github.com/BlackArch/blackarch-pkgbuilds/commit/2d95e1be135722402e7362160eb23709b66b6535

**Pull request closed without merging**
